### ISSUE TITLE
How to utilize the Sentry API?

### ISSUE THREAD

**Issue by saturnonearth** [jill64/sentry-sveltekit-cloudflare#379]
I am trying to figure out how to addUser context within the error handler - how would you do this with this package, or is this handled by something like `toucan-js`?

**Comment by jill64** [comment]
Thanks for the feedback.

There is currently no support for the Sentry API other than error capture.

This is a temporary workaround for [@sentry/javascript #8291](https://github.com/getsentry/sentry-javascript/issues/8291), as we are focusing on being able to hide the details of things and deploy them immediately in your application.

However, since [@sentry/javascript #8291](https://github.com/getsentry/sentry-javascript/issues/8291) support does not seem to be progressing, we will consider supporting it if we receive many similar requests.
